version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - notes-app
    networks:
      - notes_app
    
      

  notes-app:
    build:
      context: .
    container_name: notes-app
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - mysql  
    restart: always
    networks:
      - notes_app




  mysql:
    image: mysql
    container_name: db_cont
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - notes_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
      

volumes:
  db_data:

networks:
  notes_app: